package Modifiers;

public enum Stat 
{
	EXP,
	HEALTH, MANA,
	HP_REGEN, MP_REGEN,
	ATK, MA_ATK, DEF, MA_DEF, 
	SPEED, ATK_SPEED,
	FIRE_ATK, WATER_ATK, WIND_ATK, ELECT_ATK, SOIL_ATK,
	FIRE_DEF, WATER_DEF, WIND_DEF, ELECT_DEF, SOIL_DEF
}
